### ISSUE TITLE
Salt and hash fields still being exposed.

### ISSUE THREAD

**Issue by dnlsandiego** [saintedlama/passport-local-mongoose#100]
It seems that the salt and hash fields are still being expose when querying mongodb and setting the `select: false` option in the mongoose schema does not work on the salt and hash fields. I thought this PR: https://github.com/saintedlama/passport-local-mongoose/pull/86 fixed it since it was merged but it looks like it was reverted in the latest release.

Is there anyway to prevent the the salt and hash fields from being expose? I mean, without having to pluck them manually every query or at least have `select: false` option be respected.

I'm also curious as to why https://github.com/saintedlama/passport-local-mongoose/pull/86 was reverted because I'm currently downgrading to v1.0.2 instead of the latest to take advantage of the salt and hash fields not being expose by default but if there is a security flaw, I'd rather know and update to the latest and just have to manually pluck the salt and hash fields.

**Comment by saintedlama** [comment]
Fixed by #98

**Comment by abilicz** [comment]
Is it still a problem for anyone? It seems that the salt and hash fields are still being expose for me. Even with `select: false` like dnlsandiego mention before.

**Comment by SherloxFR** [comment]
**My setup:**
```json
{
  "os": "Ubuntu 17.10",
  "node": "9.11.1",
  "npm": "5.6.0",
  "mongoose": "4.5.9",
  "passport": "0.3.2",
  "passport-local-mongoose": "5.0.0"
}
```

Yes, obviously this is not fixed.

**Model:**
```javascript
new Schema({
  username: { type: String, unique: true },
  email: { type: String, unique: true },
  salt: { type: String, select: false },
  hash: { type: String, select: false }
})
```

**Login route:**
```javascript
async authenticate (req) {
  const { user } = await Account.authenticate('jwt')(req.body.username, req.body.password)
  const token = await utils.loginAsync(req, user)
  return { user, token }
}
```

**Response from server:**
```json
{
    "success": true,
    "user": {
        "_id": "5a8eaa368fc7904d7a3c2f97",
        "salt": "d3759a7f4940b78fb48e26d7e415104b05724ad4b719cd20bd24af6f830cd31f",
        "hash": "b206bc09bac066f711db524d5e39583427e189be382eb03c53a255e1f1e2487ba8f6f0a0380835efec7c9a137c328f4ec358a81dd3c3dcc4646832de5127f2b18a26f960e9ffa4d280b5f5db1b3d4bacb2785fc4b85a110aa5eefa030ec31d047ed055291c03f6835c68a1b08a037dc8217bbd6382a7980fd5060fd18daa3fe8cc58f4e1de9e32624b6ae3939cd869c8c8ecdd76e8d7dbcaa6767ff8f2c81aeef343bf52da3254005cedee29dd11a2f619b03b3a15c681f5a418081f634132e8a799bc706b5214f01adfb0cc55e44f1bcc8af4011aff6225d83cc566ceae244ee9a1e6448f2fd88e5a3483ae9688ddba93870f5d6a33acc4c5998cc1c43b8c1dcb603931efcc1668d388ec67bfc63b3ae1b07a3b4abb57a321fa56d15aad694b1c3d4199dd451d8a820fd6c12ea076e816dd2f9f4d516337e7c73ec932251d34b9fd84a1249720e92cb9fbc41c536c123d992cf63a41ff12b141389427d96d239487c7fe3c9afe66052ff11af0ab9c6e146223d7fae2b818a1742287295082caf96b2ffb154ada7578d7c22d34ba502b150b14106c51aafae5d6086fa40a30cdad8698fae2919bb8c6f8be3e606a05a31d9ee6ced4d24ff63d80e67508a5c87c6cbda00c8c4ba204a56b98d311be7f0653a46b112649225bada1b0ecc5023f819a47b639646f67dbec64935217545495082ccf4cd6dd73ca1a2f4ba195a7dd49",
        "username": "admin",
        "email": "me@domain.com",
        "__v": 0
    },
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...."
}
```

Seems like `select: false` from model is not taken into account.
Please reopen this issue.

**Comment by olawalejuwonm** [comment]
i'm also experiencing the same thing
